service: payment-strategy-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

plugins:
  - serverless-plugin-typescript

functions:
  processPayment:
    handler: src/handlers/processPayment.handler
    events:
      - sqs:
          arn: !GetAtt PaymentQueue.Arn
          batchSize: 1

resources:
  Resources:
    PaymentQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-payment-queue
        VisibilityTimeout: 30
        MessageRetentionPeriod: 345600 # 4 days
